<?php
$index = array(
	array("header"=>'<a href="u1_1">Aufgabe 1.1</a>', "content"=>'Fachliche Argumentation über Erfolgsprinzipien des WWW', "task"=>1),
	array("header"=>'<a href="u1_2">Aufgabe 1.2</a>', "content"=>'HTTP', "task"=>1),
	array("header"=>'<a href="u1_3">Aufgabe 1.3</a>', "content"=>'HTML-Literatur lesen und Fragen beantworten', "task"=>1),
	array("header"=>'<a href="u1_4">Aufgabe 1.4</a>', "content"=>'HTML Wireframe', "task"=>1),
	array("header"=>'<a href="u2_1">Aufgabe 2.1</a>', "content"=>'CSS Selektoren und CSS Farben', "task"=>2),
	array("header"=>'<a href="u2_2">Aufgabe 2.2 – Part 1</a>', "content"=>'CSS Positionierung', "task"=>2),
	array("header"=>'<a href="u2_3">Aufgabe 2.2 – Part 2</a>', "content"=>'CSS Positionierung', "task"=>2),
	array("header"=>'<a href="u2_4">Aufgabe 2.3</a>', "content"=>'Wireframe with HTML and CSS', "task"=>2),
	array("header"=>'<a href="u3_1">Aufgabe 3.1</a>', "content"=>'Responsiv mit Flexbox Desktop-First', "task"=>3),
	array("header"=>'<a href="u3_2">Aufgabe 3.2</a>', "content"=>'Responsiv mit Grid Mobile-First', "task"=>3),
	array("header"=>'<a href="u3_3">Aufgabe 3.3</a>', "content"=>'Responsiv mit Grid', "task"=>3),
	array("header"=>'<a href="u4_1">Aufgabe 4.1</a>', "content"=>'Funktionen', "task"=>4),
	array("header"=>'<a href="u4_2">Aufgabe 4.2</a>', "content"=>'Objekte', "task"=>4),
	array("header"=>'<a href="u4_3">Aufgabe 4.3</a>', "content"=>'Fibonacci', "task"=>4),
	array("header"=>'<a href="u4_4">Aufgabe 4.4</a>', "content"=>'Topsort', "task"=>4),
	array("header"=>'<a href="u5_1">Aufgabe 5.1</a>', "content"=>'Klasse für Vorrangrelationen', "task"=>5),
	array("header"=>'<a href="u5_2">Aufgabe 5.2</a>', "content"=>'Topologische Iterierbarkeit', "task"=>5),
	array("header"=>'<a href="u5_3">Aufgabe 5.3</a>', "content"=>'Topologischer Generator', "task"=>5),
	array("header"=>'<a href="u5_4">Aufgabe 5.4</a>', "content"=>'Proxy', "task"=>5),
	array("header"=>'<a href="u5_5">Aufgabe 5.5</a>', "content"=>'DeepCopy', "task"=>5),
	array("header"=>'<a href="u6_1">Aufgabe 6.1</a>', "content"=>'Funktionen in JavaScript', "task"=>6),
	array("header"=>'<a href="u6_2">Aufgabe 6.2</a>', "content"=>'Textanalyse mit filter-map-reduce', "task"=>6),
	array("header"=>'<a href="u7_1">Aufgabe 7.1</a>', "content"=>'Performanzmessungen von DOM-Operationen', "task"=>7),
	array("header"=>'<a href="u7_2">Aufgabe 7.2</a>', "content"=>'Rednerliste mit Zeitmessung', "task"=>7),
	array("header"=>'<a href="u7_3">Aufgabe 7.3</a>', "content"=>'TopSort als WebApp', "task"=>7),
	array("header"=>'<a href="u8_1">Aufgabe 8.1</a>', "content"=>'Promises', "task"=>8),
	array("header"=>'<a href="u8_2">Aufgabe 8.2</a>', "content"=>'async / await', "task"=>8),
	array("header"=>'<a href="u8_3">Aufgabe 8.3</a>', "content"=>'WWW-Navigator', "task"=>8),
	array("header"=>'<a href="u9_1">Aufgabe 9.1</a>', "content"=>'Komponente in Vue.js', "task"=>9),
	array("header"=>'<a href="u9_2">Aufgabe 9.2</a>', "content"=>'Menü-Komponente', "task"=>9),
	array("header"=>'<a href="u9_3">Aufgabe 9.3</a>', "content"=>'Vue.js WWW-Navigator', "task"=>9),
	array("header"=>'<a href="u10_1">Aufgabe 10.1</a>', "content"=>'Registrierung mit PHP', "task"=>10),
	array("header"=>'<a href="u10_2">Aufgabe 10.2</a>', "content"=>'Login mit PHP', "task"=>10),
	array("header"=>'<a href="u10_3">Aufgabe 10.3</a>', "content"=>'WWW-Navigator zum Content-Editor ausbauen', "task"=>10)
);
?>